<a href="https://colab.research.google.com/github/rmarharyta/machinelearning/blob/main/%D0%A0%D1%83%D0%B1%D0%BB%D0%B5%D0%BD%D0%BA%D0%BE_%D0%BB%D1%801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
import numpy as np

np.__version__


'2.1.3'

## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
arr=np.array([2,4,6,8,10])

print(arr)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
zerros=np.zeros(10)
print(zerros)

ones=np.ones(8)
print(ones)

sevens=np.full(6,7)
print(sevens)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
arr_1 = np.arange(1, 21)
print(arr_1)

arr_2 = np.arange(2, 21, 2)
print(arr_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
arr = np.linspace (0, 1, 11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

2
(3, 4)
12
int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
arr = [1.2, 3.5, 5.7, 7.9]
arr = np.array(arr).astype(int)
print(arr)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
arr = np.arange(10,81, 10)

print(arr[0])
print(arr[-1])
print(arr[2:6])
print(arr[::2])

10
80
[30 40 50 60]
[10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
matrix = np.arange(1,13).reshape(3, 4)

print(matrix[1,2])
print(matrix[1])
print(matrix[:,2])
print(matrix[1:,:2])

7
[5 6 7 8]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
arr = np.arange(1,16)
arr[5:10] = 0
print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
arr_1=np.array([1,2,3,4,5])
arr_2=np.array([10,20,30,40,50])

print(arr_1+arr_2)
print(arr_1-arr_2)
print(arr_1*arr_2)
print(arr_1/arr_2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
arr = np.array([4,8,15,16,23,42])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))


108
18.0
4
42
15.5
12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
matrix = np.arange(1,10).reshape(3,3)

print(np.sum(matrix))
print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))
print(np.mean(matrix, axis=0))

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
arr = np.arange(1,11)

print(np.multiply(arr, arr))
print(np.sqrt(arr))
print(np.log(arr))

[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
arr = np.array([3,7,12,18,21,25,30,34])

print(arr[arr>15])
print(arr[arr%2==0])
print(arr[(arr>=10) & (arr<=30)])

[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
arr = np.array([-5,3,-2,8,-1,10,0])
arr[arr<0] = 0
print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
arr = np.array(np.random.randint(0,101,20))

print(arr)

print(np.sum(arr>50))
print(np.sum(arr<=50))

[77 84 46 39 41 45 78 18 85 39 43 61 32 98 16  7 21 63 97 55]
9
11


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
arr = np.arange(1,25)

print(arr.reshape(4,6))
print(arr.reshape(6,4))
print(arr.reshape(2,3,4))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
matrix_1 = np.arange(1,5).reshape(2,2)
matrix_2 = np.arange(5,9).reshape(2,2)

print(np.vstack((matrix_1, matrix_2)))
print(np.hstack((matrix_1, matrix_2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
matrix = np.arange(1,13).reshape(3,4)

print(matrix.flatten())
print(matrix.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

print(arr_1+arr_2)
print(arr_1-arr_2)
print(arr_1*3)
print(arr_2*3)

[ 3  7 11]
[1 1 1]
[ 6 12 18]
[ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(np.dot(arr_1,arr_2))
print(arr_1@arr_2)

32
32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
arr = np.array([3,4])

print(np.linalg.norm(arr))
print(arr/np.linalg.norm(arr))

5.0
[0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
arr_1 = np.array([1,0,0])
arr_2 = np.array([0,1,0])

np.cross(arr_1,arr_2)

array([0, 0, 1])

### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
arr_1 = np.array([1,2])
arr_2 = np.array([2,1])

print(np.dot(arr_1,arr_2)/(np.linalg.norm(arr_1)*np.linalg.norm(arr_2)))

0.7999999999999998


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
matrix=np.arange(1,7).reshape(2,3)

print(matrix.T)
print(np.transpose(matrix))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
matrix_1 = np.arange(1,5).reshape(2,2)
matrix_2 = np.arange(2,6).reshape(2,2)

print(matrix_1*matrix_2)
print(matrix_1@matrix_2)

[[ 2  6]
 [12 20]]
[[10 13]
 [22 29]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
matrix = np.array([[4,7],[2,6]])

print(np.linalg.det(matrix))
print(np.linalg.inv(matrix))
print(matrix@np.linalg.inv(matrix))

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
matrxi_a = np.array([[2,1],[1,3]])
vector_b = np.array([5,6])

np.linalg.solve(matrxi_a, vector_b)

array([1.8, 1.4])

### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
matrix = np.eye(4)

print(matrix)
print(matrix@np.arange(1,17).reshape(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
matrix = np.arange(1,10).reshape(3,3)

print(matrix+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
matrix = np.arange(1,10).reshape(3,3)
arr = np.array([10,20,30])

print(matrix+arr)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
matrix = np.array([[10,20,30],[20,30,40],[30,40,50]])

print((matrix-np.mean(matrix, axis=0))/np.std(matrix, axis=0))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
np.random.seed(42)

arr = np.random.randint(1,101,10)
matrix = np.random.rand(3,3)
arr_2 = np.random.normal(size=1000)

print(arr)
print(matrix)
print(arr_2)

print(np.mean(arr_2))
print(np.std(arr_2))

[52 93 15 72 61 21 83 87 75 75]
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
[ 2.41962272e-01 -1.91328024e+00 -1.72491783e+00 -5.62287529e-01
 -1.01283112e+00  3.14247333e-01 -9.08024076e-01 -1.41230370e+00
  1.46564877e+00 -2.25776300e-01  6.75282047e-02 -1.42474819e+00
 -5.44382725e-01  1.10922590e-01 -1.15099358e+00  3.75698018e-01
 -6.00638690e-01 -2.91693750e-01 -6.01706612e-01  1.85227818e+00
 -1.34972247e-02 -1.05771093e+00  8.22544912e-01 -1.22084365e+00
  2.08863595e-01 -1.95967012e+00 -1.32818605e+00  1.96861236e-01
  7.38466580e-01  1.71368281e-01 -1.15648282e-01 -3.01103696e-01
 -1.47852199e+00 -7.19844208e-01 -4.60638771e-01  1.05712223e+00
  3.43618290e-01 -1.76304016e+00  3.24083969e-01 -3.85082280e-01
 -6.76922000e-01  6.11676289e-01  1.03099952e+00  9.31280119e-01
 -8.39217523e-01 -3.09212376e-01  3.31263431e-01  9.75545127e-01
 -4.79174238e-01 -1.85658977e-01 -1.10633497e+00 -1.19620662e+00
  8.12525822e-

### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
arr = np.random.randint(0,101,30)

print(arr)

print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr>=60))
print(np.sum(arr>=90)/len(arr)*100)

[25  2 40 59 13 74 81 11 86 11 12 24 44 18 54 99 44  7 92 52 54 31 50 43
 81 69 17 82 21 36]
44.4
43.5
2
99
8
6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
matrix = np.array([[120,150,170,160],[80,90,100,110],[200,180,210,230]])

print(np.sum(matrix, axis=1))
print(np.sum(matrix, axis=0))
print(np.argmax(np.sum(matrix, axis=1)))
print(np.argmax(np.sum(matrix, axis=0)))
print(np.mean(matrix, axis=0))

[600 380 820]
[400 420 480 500]
2
3
[133.33333333 140.         160.         166.66666667]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
matrix = np.random.randint(1,21,25).reshape(5,5)

print(matrix)

print(np.sum(np.diag(matrix)))
print(np.sum(np.diag(np.fliplr(matrix))))
print(np.max(matrix, axis=1))
print(np.min(matrix, axis=0))
print(np.where(matrix<np.mean(matrix),0,matrix))

[[ 9  3 10 19  3]
 [15  1  7 12 17]
 [20  5  4 12 20]
 [18 17 19  9  4]
 [ 2  4  2 15  2]]
25
38
[19 17 20 19 15]
[2 1 2 9 2]
[[ 0  0 10 19  0]
 [15  0  0 12 17]
 [20  0  0 12 20]
 [18 17 19  0  0]
 [ 0  0  0 15  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
matrix = np.array([[2,4,6],[1,3,5],[5,7,9]])

print(np.linalg.norm(matrix[0]-matrix[1]))
print(np.linalg.norm(matrix[0]-matrix[2]))
print(np.linalg.norm(matrix[1]-matrix[2]))

1.7320508075688772
5.196152422706632
6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
matrix = np.random.randint(1,10,16).reshape(4,4)

print(matrix)
print(matrix/np.linalg.norm(matrix, axis=1).reshape(4,1))

[[4 6 7 3]
 [3 6 3 2]
 [8 5 1 3]
 [8 4 7 2]]
[[0.38138504 0.57207755 0.66742381 0.28603878]
 [0.3939193  0.7878386  0.3939193  0.26261287]
 [0.80403025 0.50251891 0.10050378 0.30151134]
 [0.69368798 0.34684399 0.60697698 0.17342199]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
matrix_a = np.array([[1,2,1],[2,1,-1],[3, -1, 2]])
vector_b = np.array([9,8,3])

print(np.linalg.solve(matrix_a, vector_b))
print(matrix_a@np.linalg.solve(matrix_a, vector_b))
print(vector_b)

[ 2.22222222  3.44444444 -0.11111111]
[9. 8. 3.]
[9 8 3]


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
